services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin123
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"

  app:
    image: product_jvm:latest
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/products
      SPRING_DATASOURCE_USERNAME: admin123
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_LIQUIBASE_URL: jdbc:postgresql://db:5432/products
      SPRING_LIQUIBASE_USERNAME: admin123
      SPRING_LIQUIBASE_PASSWORD: admin123
      SPRING_r2dbc_URL: r2dbc:postgresql://db:5432/products
      SPRING_r2dbc_USERNAME: admin123
      SPRING_r2dbc_PASSWORD: admin123
